export const prayerList = [
    {
        id: 1,
        title: "Prayer 1",
        description: "Prayer 1 description",
        prayer: "Prayer 1 prayer",
        category: "Prayer 1 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        title: "Prayer 2",
        description: "Prayer 2 description",
        prayer: "Prayer 2 prayer",
        category: "Prayer 2 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        title: "Prayer 3",
        description: "Prayer 3 description",
        prayer: "Prayer 3 prayer",
        category: "Prayer 3 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        title: "Prayer 4",
        description: "Prayer 4 description",
        prayer: "Prayer 4 prayer",
        category: "Prayer 4 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        title: "Prayer 5",
        description: "Prayer 5 description",
        prayer: "Prayer 5 prayer",
        category: "Prayer 5 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        title: "Prayer 6",
        description: "Prayer 6 description",
        prayer: "Prayer 6 prayer",
        category: "Prayer 6 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        title: "Prayer 7",
        description: "Prayer 7 description",
        prayer: "Prayer 7 prayer",
        category: "Prayer 7 category",
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]

export const data = {
    prayerList,
}